---

- hosts: all

  tasks:
          #0 */6 * * * /opt/delete-dir.sh
    - name: send tempplate file
      template:
        src: delete-dir.j2
        dest: /opt/delete-dir.sh
        mode: '777'

    - name: set cron job for root user
      cron:
        minute: "0"
        hour: "*/6"
        job: "/opt/delete-dir.sh"
